name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '**Welcome to the Bisq project!**<br/> Thanks for taking the time to create this issue. Issues will be reviewed by the maintainers and labeled and assigned for further [contributor checklist](https://docs.bisq.network/contributor-checklist.html).'
        pr-message: '*Welcome to the Bisq project!*\n Please make yourself familiar with our [contributor checklist](https://docs.bisq.network/contributor-checklist.html) and check any issues that are found by *Travis* or *Codacy* running basic checks on your contribution. Especially check that all your commits are signed and you applied the Bisq code style and formatting.\n Not all contributions are also up for compensation right now in the Bisq DAO. Everything labeled with `is:priority` is up for compensation everything marked with `is:no-priority` or no label is not compensated right now. Please checkout our [blog post](https://bisq.network/blog/cycle-8-results/) on cycle budgets for more details.'
